lwcBundle/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>GM{000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lwcBundle/main/default/objects/Game__c/fields/Current_Turn__c.field-meta.xml
<CustomField>
    <fullName>Current_Turn__c</fullName>
    <description>X or O</description>
    <label>Current Turn</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

lwcBundle/main/default/objects/Game__c/fields/Player_O__c.field-meta.xml
<CustomField>
    <fullName>Player_O__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player_O</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Games_as_O</relationshipName>
    <type>Lookup</type>
</CustomField>

lwcBundle/main/default/objects/Game__c/fields/Player_X__c.field-meta.xml
<CustomField>
    <fullName>Player_X__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player_X</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Games_as_X</relationshipName>
    <type>Lookup</type>
</CustomField>

lwcBundle/main/default/objects/Move__c/fields/Box__c.field-meta.xml
<CustomField>
    <fullName>Box__c</fullName>
    <description>0-8</description>
    <label>Box</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

lwcBundle/main/default/objects/Move__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

lwcBundle/main/default/objects/Move__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <description>X or O</description>
    <label>Letter</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

lwcBundle/main/default/classes/TicTacToeController.cls
public with sharing class TicTacToeController {

    public class GameObject {
        public Id game;
        public String player_X;
        public String player_O; 
        public Boolean started;
        public List<Move__c> moves;

        public GameObject(Id gameId){
            Game__c currentGame = [SELECT 
                                    Id, 
                                    Current_Turn__c, 
                                    Player_X__r.Name, 
                                    Player_O__r.Name, 
                                    (SELECT Id, Box__c, Letter__c FROM Moves__r) 
                                    FROM Game__c 
                                    WHERE Id = :gameId Limit 1];
            game = gameId;
            player_X = currentGame.Player_X__r.Name;
            player_O = currentGame.Player_O__r.Name;
            moves = currentGame.Moves__r;
            started = true;
        }

        public GameObject(User Player_XUser){
            Game__c newGame = new Game__c(Player_X__c  = Player_XUser.Id);
            insert newGame;

            game = newGame.Id;
            player_X = Player_XUser.Name;

        }
    }




}